baseURL: 'https://kaue.cat'
title: Kaue Gatto
paginate: 5
defaultContentLanguage: pt
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
disqusShortname: www-kaue-cat

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kaue Gatto
  description: "Dev Backend, curto arquitetura de software e cerveja"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  defaultTheme: dark # dark, light
  disableThemeToggle: false
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter", "whatsapp"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"
  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35
  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    subtitle: "Aprendizados de um dev que curte arquitetura de software e uma boa cerveja!"
    imageUrl: "https://avatars.githubusercontent.com/u/13698473?v=4"
    imageTitle: Eu!
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
  socialIcons:
    - name: github
      url: "https://github.com/kauegatto"  
    - name: linkedin
      url: "https://www.linkedin.com/in/kaue-gatto"
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
  editPost:
    URL: "https://github.com/kauegatto/kaeudotcat/content"
    Text: "Faça Sugestões" # edit text
    appendFilePath: true # to append file path to Edit link
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary"]
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
languages:
    pt:
        languageName: "Português (Brasil)"
        weight: 0
        taxonomies:
          category: Categorias
          tag: tags
          series: series
        menu:
          main:
            - name: Arquivo
              url: archives
              weight: 5
            - name: Buscar
              url: search/
              weight: 5
            - name: Séries
              url: series/
              weight: 5
    en:
        languageName: "English"
        weight: 1
        title: Kaue Gatto - Software Engineer
        taxonomies:
          category: Categories
          tag: Tags
          series: Series
        menu:
          main:
            - name: Archive
              url: archives/
              weight: 5
            - name: Search
              url: search/
              weight: 5
            - name: Séries
              url: series/
              weight: 5
        params:
          profileMode:
              enabled: true
              imageUrl: "https://avatars.githubusercontent.com/u/13698473?v=4"
              title: Kaue Gatto - Software Engineer
              subtitle: "Coding adventures of a developer which is addicted in software development and architecture. Still WIP of parsing my texts to english"
              buttons:
                - name: Posts
                  url: posts
                - name: Tags
                  url: tags